baseURL: https://jadin.me/

menu:
    main:
        # - name: About Me
        #   url: /about
        #   pre: <span class="main-pages">
        #   post: </span>
        #   weight: 10
        - name: Bookmarks
          url: /bookmarks
          pre: <span class="main-pages">
          post: </span>
          weight: 20
        - name: Slides
          url: https://slides.jadin.me
          pre: <span class="main-pages">
          weight: 30
        - name: Posts by date
          url: /all
          weight: 40
        - name: Posts by tag
          url: /tags
          weight: 50
        - name: Search
          url: /search
          weight: 60

title: Taylor Jadin
theme:
  - PaperMod
languageCode: en-us
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
    home:
        - HTML
        - RSS
        - JSON
Permalinks:
  post: '/:slug'
params:
  defaultTheme: dark
  disableThemeToggle: true
  env: production
  comments: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  cover:
    responsiveImages: false
  homeInfoParams:
      Content1: I am the Community Instructional Technologist at Reclaim Hosting. I am passionate about educating and empowering people who want to make cool stuff on the web.

      Content2: I [tweet](https://twitter.com/taylorjadin), [post pictures to Instagram](https://www.instagram.com/taylor_jadin/), and [occasionally write code](https://github.com/taylorjadin). My wife and I also sometimes [stream](http://twitch.tv/jadinapproved) or [record a podcast](https://anchor.fm/taylor-jadin) under the name Jadin Approved.

rssLimit: 50
copyright: Taylor Jadin
languageCode: en-us
author:
  name: Taylor Jadin
  email: taylor@jadin.me
disqusShortname: https-jadin-me
googleAnalytics: UA-114305115-1