baseURL: https://jadin.me/

menu:
    main:
        # - name: About Me
        #   url: /about
        #   pre: <span class="main-pages">
        #   post: </span>
        #   weight: 10
        - name: Bookmarks
          url: https://raindrop.io/jadin-taylor/public-26229943/sort=-created&perpage=30&page=0
          pre: <span class="main-pages">
          post: </span>
          weight: 20
        - name: Video
          url: https://video.jadin.me
          pre: <span class="main-pages">
          post: </span>
          weight: 25
        - name: Slides
          url: https://slides.jadin.me
          pre: <span class="main-pages">
          weight: 30
        - name: Archive
          url: /archive
          weight: 40
        - name: Tags
          url: /tags
          weight: 50
        - name: RSS
          url: /index.xml
          weight: 55
        - name: Search
          url: /search
          weight: 60

title: Taylor Jadin
theme:
  - PaperMod
languageCode: en-us
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
Permalinks:
  posts: '/:filename'
  pages: '/:filename'
  redirects: '/:filename'
params:
  defaultTheme: dark
  disableThemeToggle: true
  env: production
  comments: true
  opengraph_io_api_key: 0f12c7d8-63f2-4b52-ac94-3af07a85960a
  ShowFullTextinRSS: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  cover:
    responsiveImages: false
  homeInfoParams:
      Content1: I work at Reclaim Hosting as our Community Instructional Technologist. I am passionate about educating and empowering people who want to make cool stuff on the web.

      Content2: I blog on this site, <a rel="me" href="https://social.ds106.us/@taylorjadin">post on Mastodon</a>, and <a rel="me" href="https://github.com/taylorjadin">occasionally write code</a>. You can also find links to my [public pbookmarks](https://raindrop.io/jadin-taylor/public-26229943/sort=-created&perpage=30&page=0), my [PeerTube site](https://video.jadin.me/) for videos and streaming, and an archive of my [slides and presentations](https://slides.jadin.me/) here.

rssLimit: 25
copyright: Taylor Jadin
author:
  name: Taylor Jadin
  email: taylor@jadin.me
disqusShortname: https-jadin-me
# googleAnalytics: UA-114305115-1
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
enableRobotsTXT: true